version: '2'

services:

  angular_app:
    container_name: node.angular.cli.dev
    volumes:
     - ./app:/var/www/app/
    build:
      context: ./
      #context: ./dockerfiles/
      dockerfile: ./dockerfiles/node.angular.cli.dockerfile.sh

    image: cntmedia/node.angular.cli:dev
    
    expose:
      - 8080
      - 8081
    ports:
      - 80:8080
      - 8080:8081
